build:
  stage: build
  script:
    - wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --quiet
    - composer install
test:
  stage: test
  script: 
  - bash <(curl -s https://blackducksoftware.github.io/hub-detect/hub-detect.sh) --blackduck.hub.url="${HUB_URL}" --blackduck.hub.username="${HUB_USERNAME}" --blackduck.hub.password="${HUB_PASSWORD}" --detect.policy.check=true