test:
  stage: test
  script: 
  - bash <(curl -s -L https://detect.synopsys.com/detect.sh) --blackduck.hub.url="${HUB_URL}" --blackduck.hub.username="${HUB_USERNAME}" --blackduck.hub.password="${HUB_PASSWORD}" --detect.policy.check=true