test:
  stage: test
  script: 
  - bash <(curl -s https://blackducksoftware.github.io/hub-detect/hub-detect.sh) --blackduck.hub.url="${HUB_URL}" --blackduck.hub.username="${HUB_USERNAME}" --blackduck.hub.password="${HUB_PASSWORD}" --detect.policy.check=true